# Dataset settings
dataset: medmnist2d
img_size: 224
num_classes: 2  # Change this per dataset
train_split: train
val_split: val
mean:
  - 0.5
  - 0.5
  - 0.5
std:
  - 0.5
  - 0.5
  - 0.5
crop_pct: 1.0
scale:
  - 0.8
  - 1.0
interpolation: bicubic
train_interpolation: random

# Data augmentation
aa: rand-m9-mstd0.5-inc1
mixup: 0.8
mixup_mode: batch
mixup_prob: 1.0
mixup_switch_prob: 0.5
mixup_off_epoch: 175
cutmix: 1.0
reprob: 0.25
remode: pixel

# Model config
model: cct_7_7x2_224_sine
model_ema: false
amp: true

# Optimization
opt: adamw
lr: 1.1e-4
min_lr: 1e-5
weight_decay: 6e-2
smoothing: 0.1
epochs: 300
batch_size: 512
sched: cosine
warmup_epochs: 10
cooldown_epochs: 10
warmup_lr: 0.000001

# Hardware
workers: 8
pin_mem: true
log_wandb: true